# Generated by Django 4.1.7 on 2023-09-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_price_orderitem_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_order_successful',
            new_name='is_payment_successful',
        ),
    ]
