# Generated by Django 4.1.7 on 2023-09-20 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_is_order_cancelled_order_cancel_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variation_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), null=True, size=None),
        ),
    ]
