# Generated by Django 4.2.7 on 2024-01-04 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCancellation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_cancel_reason", models.TextField()),
                ("is_order_cancelled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="cancel_order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_payment_successful",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_total_price",
        ),
        migrations.AddField(
            model_name="order",
            name="order_delivery_status",
            field=models.CharField(
                choices=[
                    ("Placed", "Placed"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_payment_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=50,
            ),
        ),
    ]
