# Generated by Django 4.2.7 on 2024-01-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_ordercancellation_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercancellation",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_cancels",
                to="order.order",
            ),
            preserve_default=False,
        ),
    ]
