# Generated by Django 4.2.7 on 2024-01-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_ordercancellation_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_delivery_status",
            field=models.CharField(
                choices=[
                    ("Placed", "Placed"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Placed",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ordercancellation",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_cancels",
                to="order.order",
            ),
        ),
    ]
