# Generated by Django 4.2.6 on 2024-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_total_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
