# Generated by Django 4.2.6 on 2024-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_order_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
