# Generated by Django 4.2.6 on 2024-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_alter_order_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_charge",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_total_price",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_price",
            field=models.FloatField(default=0.0),
        ),
    ]
