# Generated by Django 4.2.6 on 2024-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_rename_is_item_ordered_orderitem_is_item_cancelled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercancellation",
            name="order_cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitemcancellation",
            name="order_item_cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
